name: test_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route:
  provider:
  firebase_core:
  firebase_core_web:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  get_it:
  intl:
  reorderables:
  flutter_colorpicker:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true